process.on('uncaughtException', e => { console.error(e.message, e.where || '', e.position || ''); process.exit(1); });
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const db = new PGlite();
let checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; console.log('✓', label); };
const reject = async (fn, label) => { await assert.rejects(fn); checks++; console.log('✓', label); };
await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE ROLE service_role; CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY, email text); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid', true), '')::uuid $$;
CREATE FUNCTION public.uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;
GRANT USAGE ON SCHEMA public, auth TO authenticated, anon, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated, anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO authenticated, anon;`);
for (const file of ['v6_schema.sql', 'migrations_saas_subscriptions_2026-09-24.sql', 'migrations_saas_entitlements_2026-09-24.sql']) {
  await db.exec(readFileSync(file, 'utf8').replace(/^\s*CREATE EXTENSION[^;]*;/gim, ''));
}
await db.exec(readFileSync('migrations_saas_entitlements_2026-09-24.sql', 'utf8'));
check(true, 'Migrations exécutables et rejouables');
for (const role of ['anon', 'authenticated']) {
  await db.exec(`SET ROLE ${role};`);
  await reject(() => db.query('SELECT * FROM public.v_abonnements_etat'), `Vue de diagnostic inaccessible au rôle ${role}`);
  await db.exec('RESET ROLE;');
}
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222';
await db.query('INSERT INTO organizations(id,name) VALUES ($1,$2),($3,$4)',[A,'A',B,'B']);
const user=(await db.query("INSERT INTO auth.users VALUES (gen_random_uuid(),'test@example.invalid') RETURNING id")).rows[0].id;
await db.query("INSERT INTO organization_members(organization_id,user_id,role) VALUES ($1,$2,'owner')",[A,user]);
check(true,'Premier propriétaire autorisé');
const quote = async (org, n) => db.query("INSERT INTO quotes(organization_id,quote_number,client_name) VALUES ($1,$2,'Test') RETURNING id",[org,`DEV-${n}`]);
const q1=(await quote(A,1)).rows[0].id; await quote(A,2); await quote(A,3);
await reject(()=>quote(A,4),'Le quatrième devis est refusé côté serveur');
await db.query("UPDATE quotes SET client_name='Modifié' WHERE id=$1",[q1]);check(true,'Les devis existants restent modifiables au plafond');
await quote(B,1);check(true,'Le quota de la seconde entreprise est indépendant');
await reject(()=>db.query('UPDATE quotes SET organization_id=$1 WHERE id=$2',[B,q1]),'Un devis ne peut pas changer d’entreprise');
const project=async n=>db.query("INSERT INTO projects(organization_id,code,name) VALUES($1,$2,$2) RETURNING id",[A,n]);
const pr=(await project('P1')).rows[0].id;
await reject(()=>project('P2'),'Un seul chantier actif pendant l’essai');
await db.query("UPDATE projects SET status='completed' WHERE id=$1",[pr]);await project('P2');
await reject(()=>db.query("UPDATE projects SET status='active' WHERE id=$1",[pr]),'La réouverture respecte le plafond');
await db.query("UPDATE subscriptions SET trial_ends_at=now()-interval '1 day' WHERE organization_id=$1",[B]);
await reject(()=>quote(B,2),'Essai expiré : création refusée');
await db.query("UPDATE quotes SET client_name='Toujours accessible' WHERE organization_id=$1",[B]);check(true,'Expiration sans blocage des modifications');
const payment=(await db.query("INSERT INTO subscription_payments(organization_id,plan_id,billing_cycle,amount,provider_payment_id) VALUES ($1,'standard','monthly',19900,'provider-test') RETURNING id",[A])).rows[0].id;
const apply=(amount,currency='XOF',org=A)=>db.query('SELECT * FROM apply_verified_subscription_payment($1,$2,$3,$4,$5)',[org,payment,amount,currency,{}]);
await reject(()=>apply(null),'Un montant absent n’active rien');await reject(()=>apply(100),'Un sous-paiement n’active rien');await reject(()=>apply(19900,'EUR'),'Une autre devise n’active rien');await reject(()=>apply(19900,'XOF',B),'Un paiement ne crédite pas une autre entreprise');
await db.exec(`SET ROLE authenticated; SELECT set_config('test.uid','${user}',false);`);
await reject(()=>apply(19900),'Le navigateur ne peut pas appeler la RPC privilégiée');
await reject(()=>db.query("UPDATE subscriptions SET plan_id='entreprise' WHERE organization_id=$1",[A]),'Le navigateur ne peut pas modifier sa formule');
check((await db.query('SELECT organization_id FROM subscriptions')).rows.length===1,'RLS : seul l’abonnement de son entreprise est lisible');
await db.exec('RESET ROLE; SET ROLE service_role;');
const paid=(await apply(19900)).rows[0];check(paid.plan_id==='standard' && paid.status==='active','Paiement vérifié : activation atomique');
const repeat=(await apply(19900)).rows[0];check(String(repeat.current_period_end)===String(paid.current_period_end),'Rejouer le paiement ne prolonge pas deux fois');
await db.exec('RESET ROLE;');
await quote(A,4);check(true,'Standard autorise des devis au-delà du quota d’essai');
for(let i=0;i<4;i++) await db.query("WITH u AS(INSERT INTO auth.users VALUES(gen_random_uuid(),'seat@example.invalid') RETURNING id) INSERT INTO organization_members(organization_id,user_id,role) SELECT $1,id,'viewer' FROM u",[A]);
await reject(()=>db.query("WITH u AS(INSERT INTO auth.users VALUES(gen_random_uuid(),'extra@example.invalid') RETURNING id) INSERT INTO organization_members(organization_id,user_id,role) SELECT $1,id,'viewer' FROM u",[A]),'Standard limite l’équipe à cinq personnes');
// Provoquer une panne de la deuxième écriture pour vérifier le rollback des deux.
const payment2=(await db.query("INSERT INTO subscription_payments(organization_id,plan_id,billing_cycle,amount,provider_payment_id) VALUES($1,'standard','monthly',19900,'rollback-test') RETURNING id",[A])).rows[0].id;
await db.exec("CREATE FUNCTION test_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'simulated outage'; END $$; CREATE TRIGGER test_failure BEFORE UPDATE ON subscription_payments FOR EACH ROW EXECUTE FUNCTION test_failure();");
await reject(()=>db.query('SELECT * FROM apply_verified_subscription_payment($1,$2,19900,\'XOF\',\'{}\')',[A,payment2]),'Panne d’écriture simulée');
const after=(await db.query('SELECT current_period_end FROM subscriptions WHERE organization_id=$1',[A])).rows[0];
check(String(after.current_period_end)===String(paid.current_period_end),'Panne : aucune prolongation partielle');
check((await db.query('SELECT applied_at FROM subscription_payments WHERE id=$1',[payment2])).rows[0].applied_at===null,'Panne : le paiement reste réessayable');
await db.exec('DROP TRIGGER test_failure ON subscription_payments;');
await db.query('SELECT * FROM apply_verified_subscription_payment($1,$2,19900,\'XOF\',\'{}\')',[A,payment2]);
check((await db.query('SELECT applied_at FROM subscription_payments WHERE id=$1',[payment2])).rows[0].applied_at!==null,'Le rejeu après panne réussit');
await db.close();
const storage=new Map([['ikadevis_subscription',JSON.stringify({planId:'entreprise',status:'active'})]]);
const context={console, localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},CustomEvent:class{constructor(type,o){this.detail=o.detail;}}, window:{dispatchEvent(){}},Date};
vm.createContext(context);vm.runInContext(readFileSync('js/subscription-service.js','utf8'),context);
const service=context.SubscriptionService;
service.setContext('userA',A);check(service.getSubscription().planId==='starter','Ancien cache global ignoré');
service.saveSubscription({planId:'standard',status:'active',expiresAt:Date.now()+86400000});
service.setContext('userA',B);check(service.getSubscription().planId==='starter','Cache isolé par entreprise');
service.setContext('userB',A);check(service.getSubscription().planId==='starter','Cache isolé par utilisateur');
service.setContext('userA',A);check(service.getSubscription().planId==='standard','Retour sur le bon cache');
let resolve;
service.setSupabaseClient({functions:{invoke:()=>new Promise(r=>{resolve=r})}});
const request=service.refreshFromServer();service.setContext('userA',B);
resolve({data:{subscription:{organization_id:A,plan_id:'entreprise',status:'active'}}});await request;
check(service.getSubscription().planId==='starter','Une réponse tardive ne contamine pas l’entreprise courante');
service.saveSubscription({planId:'standard',status:'cancelled'});check(!service.canCreateDevis(0).allowed,'Abonnement annulé : interface cohérente');
console.log(`\n${checks} contrôles réussis.`);
