import vm from 'node:vm';
import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const ctx={console,crypto:globalThis.crypto};vm.createContext(ctx);
for(const f of ['js/finance-core.js','js/quote-import.js','js/project-profitability.js','js/vendor/xlsx-0.20.3.min.js','js/calc-engine.js'])vm.runInContext(readFileSync(f,'utf8'),ctx);
let count=0;const check=(v,m)=>{assert.ok(v,m);count++;console.log('✓',m);};
const I=ctx.QuoteImport;
const csv=readFileSync('assets/templates/bordereau-ikadevis.csv','utf8');const rows=I.parseText(csv);const mapping=I.mapHeaders(rows[0]);
let p=I.preview(rows,0,mapping);check(p.valid&&p.lines.length===3,'Modèle CSV : colonnes reconnues et trois ouvrages');check(p.total===1217500,'Total HT importé exact');check(p.missingCosts===1,'Coût absent signalé sans inventer de marge');
const lots=I.toLots(p,'test.csv');check(lots.length===2&&lots[0].items.length===2,'Regroupement par lot');
check(I.number('1\u202f234,56')===1234.56,'Décimales et espaces français');check(I.number('1,234.56')===1234.56,'Décimales internationales');check(Number.isNaN(I.number('12abc')),'Montant malformé refusé');check(Number.isNaN(I.number('1,2,3')),'Séparateurs ambigus refusés');
const multiline=I.parseText('Désignation;Unité;Quantité;PU HT\n"Béton; \"\"spécial\"\"\nchantier";m3;2;100');check(multiline[1][0]==='Béton; "spécial"\nchantier','CSV guillemets, séparateur et saut de ligne');
assert.throws(()=>I.parseText('A;B\n"sans fin'));count++;
const invalid=I.parseText('Désignation;Unité;Quantité;PU HT\nBéton;m3;2;100\nTotal;;;200');p=I.preview(invalid,0,I.mapHeaders(invalid[0]));check(!p.valid,'Sous-total non importé silencieusement');p=I.preview(invalid,0,I.mapHeaders(invalid[0]),[3]);check(p.valid&&p.total===200,'Exclusion explicite du sous-total');
let wrong=rows.map(r=>[...r]);wrong[1][6]=123;check(!I.preview(wrong,0,mapping).valid,'Écart avec le montant du fichier bloquant');
wrong=rows.map(r=>[...r]);wrong[1][3]=-1;check(!I.preview(wrong,0,mapping).valid,'Quantité négative bloquée');
check(!I.preview(rows,0,{...mapping,qty:mapping.price}).valid,'Correspondance ambiguë bloquée');
check(!I.preview(rows,0,{...mapping,qty:''}).valid,'BPU sans quantités à compléter avant import');
const calc=ctx.calculateHybridQuote({lots,vatRate:18,overheadRate:5,margin:30},[],[],[],[]);
check(calc.totalNetHT===1217500,'Le moteur conserve les prix de vente importés');
check(calc.totalTTC===1436650,'TVA appliquée une seule fois');
const saved=ctx.adaptHybridToSavedQuote(calc,{currency:'FCFA'});const restored=ctx.adaptSavedQuoteToHybrid(saved,[],[],[],[]);
check(restored.totalNetHT===calc.totalNetHT&&restored.lots[1].items[0].costUnit==='','Enregistrement/reprise : montants et coût inconnu conservés');
const zero=ctx.calculateSingleWorkItem({isCustom:true,name:'Test',qty:2,unitPriceHT:100,costUnit:0},[],[],[],[],{overheadRate:5});check(zero.quoteData.margeValeurConsomme===200,'Coût explicitement nul distinct du coût absent');
const XLSX=ctx.XLSX;const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Bordereau');
mkdirSync('/tmp/ikadevis-priorities-tests',{recursive:true});
const buffer=XLSX.write(book,{bookType:'xlsx',type:'buffer'});writeFileSync('/tmp/ikadevis-priorities-tests/bordereau.xlsx',buffer);
const sheets=await I.readFile({name:'bordereau.xlsx',size:buffer.length,arrayBuffer:async()=>buffer});check(sheets.length===1&&I.preview(sheets[0].rows,0,mapping).total===1217500,'Fichier XLSX réel lu correctement');
await assert.rejects(()=>I.readFile({name:'grand.xlsx',size:6*1024*1024}));count++;
const project={id:'p1',name:'Villa'},projects=[project,{id:'p2',name:'École'}];
const Q={id:'q1',projectId:'p1',status:'accepted',companyInfoSnapshot:{currency:'FCFA'},quoteData:{netHTConsomme:1000000,totalDebourseConsomme:600000,totalRevientConsomme:630000},hybridQuoteSnapshot:{lots:[{items:[{isCustom:true,costUnit:600000}]}]}};
const E=[{id:'e1',kind:'expense',description:'Béton',project_id:'p1',currency:'XOF',amount_ht:100000,amount_ttc:118000,tax_recoverable:true,reglements:[{amount:118000}]}, {id:'e2',kind:'supplier_invoice',description:'Acier',currency:'XOF',amount_ht:200000,amount_ttc:236000,tax_recoverable:true,splits:[{project_id:'p1',amount:150000},{project_id:'p2',amount:50000}]}, {id:'e3',kind:'expense',description:'Transport',project_id:'p1',currency:'XOF',amount_ht:10000,amount_ttc:11800,tax_recoverable:false,advanced_by:'Entrepreneur',reglements:[{amount:11800}]}, {id:'e4',kind:'expense',description:'Outillage',project_id:'p1',currency:'EUR',base_currency:'XOF',fx_rate:655.957,amount_ht:10,amount_ttc:10}];
const P=ctx.ProjectProfitability;
let result=P.calculate({project,projects,quote:Q,expenses:E,currency:'FCFA',remaining:50000});
check(result.actual===268360,'Coûts : TVA récupérable exclue, TVA non récupérable incluse, conversion et répartition');check(result.margin===370000,'Marge prévue avec frais généraux');check(result.projected===681640,'Projection avec reste à dépenser');check(result.rows.length===4,'Facture impayée et avance personnelle comptées une fois');
check(P.calculate({project,projects,quote:Q,expenses:[...E,{...E[0],id:'cancel',status:'cancelled'}],currency:'XOF'}).actual===268360,'Dépense annulée exclue');
check(P.calculate({project,projects,quote:Q,expenses:[{...E[0],organization_id:'other'}],currency:'XOF',organizationId:'org'}).actual===0,'Dépenses d’une autre entreprise exclues');
result=P.calculate({project,projects,quote:Q,expenses:[{...E[3],fx_rate:null}],currency:'XOF'});check(result.actual===0&&result.warnings.length===1,'Conversion absente signalée');
result=P.calculate({project,projects,quote:{...Q,hybridQuoteSnapshot:{lots:[{items:[{isCustom:true,costUnit:''}]}]}},expenses:E,currency:'XOF'});check(result.planned===null&&result.margin===null,'Coût manquant : aucune marge prévue fabriquée');
check(P.calculate({project,projects,quote:Q,expenses:E,currency:'XOF',remaining:''}).projected===null,'Pas de projection sans reste à dépenser saisi');
check(!P.quoteMatches({...Q,projectId:'other',projectRef:'Villa'},project,projects),'L’identifiant prime sur un nom de chantier homonyme');
check(!P.quoteMatches({...Q,projectId:null,projectRef:'Villa'},project,[project,{id:'other',name:'Villa'}]),'Homonymes : aucun rattachement au hasard');
check(P.calculate({project,projects,quote:{...Q,companyInfoSnapshot:{currency:'EUR'}},expenses:E,currency:'XOF'}).sales===null,'Devis dans une autre devise : comparaison bloquée');
console.log(`\n${count} contrôles réussis.`);
